first three career pages html files
Dufuna-CodeCamp/NigerII-20-Hack2 pull request #3
Opened 2020-08-29 16:25 UTC by JoyChukwukere

2020-08-29 17:58 UTC, goke-epapa commented
Please update the PR title to be more descriptive and add a description to the PR

Suggestion:
> Basic career pages with images

2020-08-29 19:10 UTC, faithakinbobola requested changes
You only changed the image folder.  You've not renamed it in your html files

2020-08-29 19:11 UTC, JoyChukwukere commented
OKAY

2020-08-29 19:12 UTC, Iyiola-stack approved these changes

2020-08-29 20:15 UTC, goke-epapa requested changes
Please review your HTML tags for all files and confirm you are using lowercase and not uppercase for any of them.

2020-08-29 20:15 UTC, goke-epapa commented on ProductDevelopment.html
> +        <img src="./image/ProductManagement.png" alt="">
Missing an `alt` text - https://www.w3schools.com/tags/att_img_alt.asp

2020-08-29 20:15 UTC, goke-epapa commented on UiUx.html
> +        <img src="./image/UiUx.png" alt="">
Missing alt text - https://www.w3schools.com/tags/att_img_alt.asp

2020-08-29 20:15 UTC, goke-epapa commented on WebDevelopment.html
> +        <img src="./image/Web Develoipment.png" alt="">
Missing alt text - https://www.w3schools.com/tags/att_img_alt.asp

2020-08-29 20:15 UTC, goke-epapa commented on ProductDevelopment.html
> +            NYou don’t need a degree in economics to be a product manager (although that degree couldn’t hurt, either), but you
```suggestion
            You don’t need a degree in economics to be a product manager (although that degree couldn’t hurt, either), but you
```

2020-08-29 20:15 UTC, goke-epapa commented on ProductDevelopment.html
> +                AProduct management is a sweeping discipline. There are many ways to approach product development, so getting started can
```suggestion
                Product management is a sweeping discipline. There are many ways to approach product development, so getting started can
```

2020-08-29 20:15 UTC, goke-epapa commented on WebDevelopment.html
> +                GROW YOUR WEB DEVELOPMENT SKILLSUnderline</a>
```suggestion
                GROW YOUR WEB DEVELOPMENT SKILLS</a>
```

2020-08-29 20:15 UTC, goke-epapa commented on WebDevelopment.html
> +            <a href="https://www.udemy.com/?utm_source=adwords&utm_medium=udemyads&utm_campaign=Generic-Broad_la.EN_cc.ROW&utm_content=deal4584&utm_term=_._ag_86841142536_._ad_405920124403_._kw_learn
The URL is too long and also contains info you don't need
```suggestion
            <a href="https://www.udemy.com">Web Development
```

2020-08-29 20:15 UTC, goke-epapa commented on WebDevelopment.html
> +            <a href="https://www.codecademy.com/learn/paths/web-development?g_acctid=243-039-7011&g_keywordid=kwd-12372542&g_adid=435749871538&g_keyword=web%20development%20courses&g_campaign=ROW+Car
```suggestion
            <a href="https://www.codecademy.com/learn/paths/web-development">Learn
```

2020-08-29 20:15 UTC, goke-epapa commented on WebDevelopment.html
> +                href="https://www.pluralsight.com/browse/software-development/web-development?aid=7010a000002LUv2AAG&promo=&utm_source=non_branded&utm_medium=digital_paid_search_google&utm_campaign=X
```suggestion
                href="https://www.pluralsight.com/browse/software-development/web-development">Getting
```

2020-08-29 20:15 UTC, goke-epapa commented on WebDevelopment.html
> +            <P>The following courses would help you in your career as UI/UX designe></P>
```suggestion
            <p>The following courses would help you in your career as UI/UX designer</p>
```

2020-08-29 20:15 UTC, goke-epapa commented on WebDevelopment.html
> +            <P>
```suggestion
            <p>
```

2020-08-29 20:15 UTC, goke-epapa commented on WebDevelopment.html
> +            </P>
```suggestion
            </p>
```

2020-08-29 20:15 UTC, goke-epapa commented on ProductDevelopment.html
> +                href="https://www.udemy.com/course/the-complete-product-management-course/?gclid=Cj0KCQjw-af6BRC5ARIsAALPIlXF4ua_SIYNOgEgfDPh7thpZ0dnGxv_1S9odlqKMw9rFMeaOi9Hl5QaAjnbEALw_wcB&matchtype
```suggestion
                href="https://www.udemy.com/course/the-complete-product-management-course">Getting
```

2020-08-29 20:15 UTC, goke-epapa commented on UiUx.html
> +                    href="https://www.pluralsight.com/courses/getting-started-ux-design?aid=7010a000002LUv2AAG&promo=&utm_source=non_branded&utm_medium=digital_paid_search_google&utm_campaign=XYZ_EME
```suggestion
                    href="https://www.pluralsight.com/courses/getting-started-ux-design">Getting
```

2020-08-29 20:15 UTC, goke-epapa commented on UiUx.html
> +                    href="https://www.udemy.com/course/the-complete-app-design-course-ux-and-ui-design/?utm_source=adwords&utm_medium=udemyads&utm_campaign=LongTail_la.EN_cc.ROW&utm_content=deal4584&
```suggestion
                    href="https://www.udemy.com/course/the-complete-app-design-course-ux-and-ui-design">The
```

2020-08-29 20:15 UTC, goke-epapa commented on UiUx.html
> +                    href="https://www.interaction-design.org/courses?ad-set=ui-ux-courses&gclid=Cj0KCQjw-af6BRC5ARIsAALPIlUUAoHuqD_RENtwImobVrdsOf_r1cwDZrhJxaV7Pr8wNaJ18jdOPpMaApaZEALw_wcB">Learn
```suggestion
                    href="https://www.interaction-design.org/courses">Learn
```

2020-08-29 20:15 UTC, goke-epapa commented on ProductDevelopment.html
> +        <P>
```suggestion
        <p>
```

2020-08-29 20:15 UTC, goke-epapa commented on ProductDevelopment.html
> +        </P>
```suggestion
        </p>
```

2020-08-29 20:15 UTC, goke-epapa commented on ProductDevelopment.html
> +        <H2>SKILLS</H2>
```suggestion
        <h2>SKILLS</h2>
```

2020-08-29 20:15 UTC, goke-epapa commented on ProductDevelopment.html
> +                <Ul>
```suggestion
                <ul>
```

2020-08-29 20:15 UTC, goke-epapa commented on ProductDevelopment.html
> +                </Ul>
```suggestion
                </ul>
```

2020-08-29 20:15 UTC, goke-epapa commented on ProductDevelopment.html
> +            <P>
```suggestion
            <p>
```

2020-08-29 20:15 UTC, goke-epapa commented on ProductDevelopment.html
> +            </P>
```suggestion
            </p>
```

2020-08-29 20:15 UTC, goke-epapa commented on ProductDevelopment.html
> +            <H2>COURSES</H2>
```suggestion
            <h2>COURSES</h2>
```

2020-08-29 20:15 UTC, goke-epapa commented on ProductDevelopment.html
> +            <P>The following courses would help you in your career as UI/UX designe></P>
```suggestion
            <p>The following courses would help you in your career as UI/UX designe></p>
```

2020-08-29 20:23 UTC, JoyChukwukere commented on ProductDevelopment.html
> +            NYou don’t need a degree in economics to be a product manager (although that degree couldn’t hurt, either), but you
okay

2020-08-29 20:32 UTC, JoyChukwukere commented on ProductDevelopment.html
> +            <P>The following courses would help you in your career as UI/UX designe></P>
Please what is wrong with this tag?

2020-08-29 20:44 UTC, goke-epapa commented on ProductDevelopment.html
> +            <P>The following courses would help you in your career as UI/UX designe></P>
it's in uppercase instead of lower case

2020-08-29 20:46 UTC, JoyChukwukere commented on ProductDevelopment.html
> +            </P>
please what do you want me to do here?

2020-08-30 10:37 UTC, faithakinbobola approved these changes

2020-08-30 15:17 UTC, goke-epapa approved these changes

2020-08-30 15:27 UTC, merged