css file for the waitList page
Dufuna-CodeCamp/NigerII-20-Hack2 pull request #7
Opened 2020-08-29 20:21 UTC by ainobs

2020-08-29 21:48 UTC, Cynthia-Berry approved these changes

2020-08-29 21:48 UTC, Cynthia-Berry commented on waitList/style.css
> +    font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
I will advice we all agree as to what font-family to use for uniformity.
Thank you so much.
This looks nice.

Can we also try handling the responsive view and a snapshot of our work?

2020-08-30 08:16 UTC, faithakinbobola requested changes
your css file should not be in a folder. Do a "git pull" and add your code to the existing style.css file.
Take note of the font family and color also, it doesn't align with that of the homepage

2020-08-30 12:28 UTC, ainobs commented
![Screenshot (24)](https://user-images.githubusercontent.com/64330690/91658998-b3d82d00-eac4-11ea-9507-98678ce587e5.png)
![Screenshot (25)](https://user-images.githubusercontent.com/64330690/91659001-b5a1f080-eac4-11ea-9e94-57c89738f3e1.png)

2020-08-30 15:47 UTC, ainobs commented
![Screenshot (27)](https://user-images.githubusercontent.com/64330690/91663398-813c2d80-eae0-11ea-8e64-b5e2604d2ec3.png)

2020-08-30 15:50 UTC, faithakinbobola approved these changes

2020-08-30 15:50 UTC, merged